/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
  public static void main(String[] args) {
    java.util.Scanner scn = new java.util.Scanner(System.in);
    
    System.out.print("번호? ");
    int num = scn.nextInt();
    
    scn.nextLine();
    
    System.out.print("수업명? ");
    String cName = scn.nextLine();
    
    System.out.print("설명? ");
    String explan = scn.nextLine();
    
    System.out.print("시작일? ");
    String sDate = scn.nextLine();

    System.out.print("종료일? ");
    String dDate = scn.nextLine();
    
    System.out.print("총수업시간? ");
    int totalLectureTime = scn.nextInt();
    
    System.out.print("일수업시간? ");
    int dayLectureTime = scn.nextInt();
    System.out.println();
    System.out.println("번호 : " + num);
    System.out.println("수업명 : " + cName);
    System.out.println("설명 : " + explan);
    System.out.printf("기간 : %s ~ %s\n",sDate, dDate);
    System.out.println("총 수업시간 : " + totalLectureTime);
    System.out.println("일 수업시간 : " + dayLectureTime);
    }
}
